client:
  service-url:
    defaultZone: http://3.109.246.230:8761/eureka/
spring:
  zipkin:
    baseUrl: http://zipkin-server:9411/
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: *
