eureka:
  client:
    service-url:
      defaultZone: http://18.217.98.177:8761/eureka/
spring:
  zipkin:
    baseUrl: http://zipkin-server:9411
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: *
