eureka:
  client:
    service-url:
      defaultZone: http://18.217.98.177:8761/eureka/
spring:
  zipkin:
    baseUrl: 3.144.230.74:9411:9411
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: *
