eureka:
  client:
    service-url:
      defaultZone: http://springboot-aws-deploy-discovery-server:8761/eureka/
spring:
  zipkin:
    baseUrl: http://zipkin-server:9411
  sleuth:
    sampler:
      probability: 1.0
