spring:
  kafka:
      consumer:
        bootstrap-servers: localhost:9092
        group-id: jt-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring:
            json:
              value:
                default:
                  type: 'springboot.microservices.notificationservice.dtos.MealPlanDTO'
              type:
                mapping: 'springboot.microservices.mealPlanningService.dto.mealDto.MealPlanDTO:springboot.microservices.notificationservice.dtos.MealPlanDTO'
